### ISSUE TITLE
Create a virtual Raspberry Pi for easy testing of communication between the Pi and mobile app.

### ISSUE THREAD

**Issue by Lionel1232** [IRTSA-SoftwareProject/IRTSA-Server#3]
# Create a virtual Raspberry Pi for easy testing of communication between the Pi and mobile app.

## Description
If possible, it would be great to have a virtualised Pi for easy testing of the mobile app. This would be really helpful for app development, as it will likely crash if making calls to the pi which is not connected (making it very difficult to develop).

## Justification
Will greatly assist with app development.

**Comment by Casper-P** [comment]
### Update
 - Setup scripts for setting up a virtual machine have been created with basic instructions located in the script file (pi_setup_vm.sh) and detailed instructions for setup located in the in the repositories readme.md file.

 - This virtual machine includes all features that a Raspberry Pi will have except for the functionality of a WAP.
